"""
Multilingual Localization Dictionary and Presentation Helpers for LexiGuard Phase 3.
Supports English (en), Hindi (hi), Kannada (kn), and Telugu (te).

CRITICAL LEGAL SAFETY DESIGN:
- The canonical source document and stored database evidence remain 100% language-neutral.
- Deterministic analysis (risk rules, relationships, financial extraction, consistency) operates in English/neutral form.
- Translation applies ONLY to presentation UI labels and generative AI explanation prompts.
- Original evidence quotes and structural citations [Section X, Page Y] remain un-overwritten.
"""
import logging
from typing import Dict, Any, Optional

logger = logging.getLogger(__name__)

SUPPORTED_LANGUAGES = {"en": "English"}

UI_TRANSLATIONS: Dict[str, Dict[str, str]] = {   'en': {   'app_title': 'LexiGuard — Legal Document Intelligence',
              'dashboard': 'Dashboard',
              'analyze': 'Analyze',
              'ask': 'Ask',
              'compare': 'Compare',
              'workspace': 'Workspace',
              'prepare': 'Prepare',
              'reports': 'Reports',
              'reminders': 'Reminders & Calendar',
              'overview': 'Overview',
              'attention_signals': 'Attention Signals',
              'relationships': 'Clause Relationships',
              'financial_compensation': 'Financial & Compensation',
              'clauses': 'Clauses',
              'consistency': 'Consistency Engine',
              'view_source': 'View Source Clause',
              'view_related': 'View Related Clause',
              'explain_ai': 'Explain with AI',
              'explain_again': 'Explain Again',
              'export_report': 'Export Report',
              'export_pdf': 'Download PDF Report',
              'export_json': 'Export JSON Data',
              'export_ics': 'Export Calendar (.ics)',
              'no_results': 'No corresponding provisions identified.',
              'insufficient_evidence': 'Insufficient evidence in the uploaded document.',
              'potential_asymmetry': 'Potential Asymmetry',
              'balanced_relationship': 'Balanced Relationship',
              'missing_counterpart': 'Missing Counterpart',
              'disclaimer_title': 'Legal Disclaimer',
              'disclaimer_text': 'LexiGuard provides document analysis and evidence-grounded explanations. It does not '
                                 'provide legal advice.',
              'hero_title': 'Understand your legal documents',
              'hero_subtitle': 'See the risks. Ask better questions. Stay protected.',
              'upload_title': 'Drag & drop your document here',
              'upload_hint': 'Supports PDF, DOCX, TXT up to 10MB',
              'browse_files': 'Browse Files',
              'recent_documents': 'Recent Documents',
              'documents': 'Documents',
              'upload': 'Upload',
              'open': 'Open',
              'delete': 'Delete',
              'pages': 'Pages',
              'financial_items': 'Financial Items',
              'generate_summary': 'Generate Summary',
              'ai_summary': 'AI Summary',
              'doc_map': 'Document Map',
              'important_dates': 'Important Dates',
              'key_obligations': 'Key Obligations',
              'ask_title': 'Ask a question about your document',
              'ask_placeholder': 'Type your legal question here...',
              'send': 'Send',
              'compare_docs': 'Compare Documents',
              'orig_doc': 'Original Document (Doc A)',
              'revised_doc': 'Revised Document (Doc B)',
              'btn_compare': 'Compare Documents',
              'added': 'Added',
              'removed': 'Removed',
              'modified': 'Modified',
              'unchanged': 'Unchanged',
              'prep_review': 'Preparation & Review',
              'gen_checklist': 'Generate Legal Review Checklist',
              'copy_clipboard': 'Copy to Clipboard',
              'evidence_viewer': 'Document Evidence Viewer',
              'doc_overview_title': 'Document Understanding Overview',
              'risk_signals': 'Risk Signals',
              'monetary_values': 'Monetary Values',
              'contracting_parties': 'Contracting Parties',
              'dates_temporal_title': 'Important Dates & Temporal Obligations',
              'review': 'Review',
              'confirm_obligation': 'Confirm Obligation',
              'track_date': 'Track Important Date',
              'view_in_doc': 'View in document',
              'why_seeing_this': 'WHY AM I SEEING THIS? ▼',
              'hide_explanation': 'HIDE EXPLANATION ▲',
              'explanation_provenance': 'EXPLANATION & PROVENANCE ▼',
              'suggested_verification': 'Suggested Verification Question',
              'general_review': 'General Review',
              'payment_terms': 'Payment Terms',
              'lawyer_questions': 'Questions for Lawyer',
              'amount': 'Amount',
              'currency': 'Currency',
              'frequency': 'Frequency',
              'effective_date': 'Effective Date',
              'timing': 'Timing',
              'condition': 'Condition',
              'section': 'Section',
              'page': 'Page',
              'not_specified': 'Not specified',
              'completeness_observation': 'Completeness Observation',
              'notice_period': 'Notice Period',
              'payment_date': 'Payment Date',
              'probation_service_period': 'Probation / Service Period',
              'deadline': 'Deadline',
              'temporal_obligation': 'Temporal Obligation',
              'none_detected': 'None detected',
              'no_structure_detected': 'No structure detected',
              'no_signals_detected': 'No attention signals or high-risk patterns detected in this document.',
              'no_relationships_detected': 'No meaningful clause relationships were identified in this document.',
              'no_financial_detected': 'No structured compensation or financial provisions identified in this '
                                       'document.',
              'select_doc_a': 'Select Document A (Original)...',
              'select_doc_b': 'Select Document B (Revised)...',
              'select_a_doc': 'Select a document...',
              'all_changes': 'All Changes',
              'financial_change_label': 'Financial Change',
              'relationship_impact_label': 'Structural / Relationship Impact',
              'explain_change_ai': 'Explain Change with AI',
              'clause_search_placeholder': 'Search document...',
              'cited_evidence_quote': 'Cited Evidence Quote:'},
    'hi': {   'app_title': 'लेक्सीगार्ड — कानूनी दस्तावेज़ इंटेलिजेंस',
              'dashboard': 'डैशबोर्ड',
              'analyze': 'विश्लेषण',
              'ask': 'प्रश्न पूछें',
              'compare': 'तुलना करें',
              'workspace': 'कार्यक्षेत्र (वर्कस्पेस)',
              'prepare': 'तैयारी',
              'reports': 'रिपोर्ट्स',
              'reminders': 'स्मरणपत्र एवं कैलेंडर',
              'overview': 'अवलोकन',
              'attention_signals': 'ध्यान देने योग्य संकेत',
              'relationships': 'धारा संबंध (क्लॉज़ रिलेशनशिप)',
              'financial_compensation': 'वित्तीय एवं मुआवजा',
              'clauses': 'धाराएं (क्लॉज़)',
              'consistency': 'संगतता इंजन (कंसिस्टेंसी)',
              'view_source': 'मूल धारा देखें',
              'view_related': 'संबंधित धारा देखें',
              'explain_ai': 'एआई से समझें',
              'explain_again': 'पुनः व्याख्या करें',
              'export_report': 'रिपोर्ट निर्यात करें',
              'export_pdf': 'पीडीएफ रिपोर्ट डाउनलोड करें',
              'export_json': 'जेसन डेटा निर्यात करें',
              'export_ics': 'कैलेंडर (.ics) निर्यात करें',
              'no_results': 'कोई संबंधित प्रावधान नहीं मिला।',
              'insufficient_evidence': 'अपलोड किए गए दस्तावेज़ में पर्याप्त साक्ष्य नहीं हैं।',
              'potential_asymmetry': 'संभावित विषमता',
              'balanced_relationship': 'संतुलित संबंध',
              'missing_counterpart': 'अनुपस्थित समकक्ष',
              'disclaimer_title': 'कानूनी अस्वीकरण',
              'disclaimer_text': 'लेक्सीगार्ड दस्तावेज़ विश्लेषण और साक्ष्य-आधारित व्याख्याएं प्रदान करता है। यह '
                                 'कानूनी सलाह प्रदान नहीं करता है।',
              'hero_title': 'अपने कानूनी दस्तावेज़ों को समझें',
              'hero_subtitle': 'जोखिम देखें। बेहतर सवाल पूछें। सुरक्षित रहें।',
              'upload_title': 'अपना दस्तावेज़ यहाँ ड्रैग और ड्रॉप करें',
              'upload_hint': 'PDF, DOCX, TXT 10MB तक समर्थित है',
              'browse_files': 'फ़ाइलें ब्राउज़ करें',
              'recent_documents': 'हाल के दस्तावेज़',
              'documents': 'दस्तावेज़',
              'upload': 'अपलोड करें',
              'open': 'खोलें',
              'delete': 'हटाएं',
              'pages': 'पृष्ठ',
              'financial_items': 'वित्तीय आइटम',
              'generate_summary': 'सारांश जनरेट करें',
              'ai_summary': 'एआई सारांश',
              'doc_map': 'दस्तावेज़ मानचित्र',
              'important_dates': 'महत्वपूर्ण तिथियां',
              'key_obligations': 'प्रमुख जिम्मेदारियां',
              'ask_title': 'अपने दस्तावेज़ के बारे में प्रश्न पूछें',
              'ask_placeholder': 'अपना कानूनी प्रश्न यहाँ टाइप करें...',
              'send': 'भेजें',
              'compare_docs': 'दस्तावेज़ों की तुलना करें',
              'orig_doc': 'मूल दस्तावेज़ (दस्तावेज़ A)',
              'revised_doc': 'संशोधित दस्तावेज़ (दस्तावेज़ B)',
              'btn_compare': 'दस्तावेज़ों की तुलना करें',
              'added': 'जोड़ा गया',
              'removed': 'हटाया गया',
              'modified': 'संशोधित',
              'unchanged': 'अपरिवर्तित',
              'prep_review': 'तैयारी और समीक्षा',
              'gen_checklist': 'कानूनी समीक्षा चेकलिस्ट जनरेट करें',
              'copy_clipboard': 'क्लिपबोर्ड पर कॉपी करें',
              'evidence_viewer': 'दस्तावेज़ साक्ष्य दर्शक',
              'doc_overview_title': 'दस्तावेज़ समझ अवलोकन',
              'risk_signals': 'जोखिम संकेत',
              'monetary_values': 'वित्तीय मूल्य',
              'contracting_parties': 'अनुबंधकर्ता पक्ष',
              'dates_temporal_title': 'महत्वपूर्ण तिथियां एवं समय दायित्व',
              'review': 'समीक्षा करें',
              'confirm_obligation': 'दायित्व की पुष्टि करें',
              'track_date': 'महत्वपूर्ण तिथि ट्रैक करें',
              'view_in_doc': 'दस्तावेज़ में देखें',
              'why_seeing_this': 'मैं यह क्यों देख रहा हूँ? ▼',
              'hide_explanation': 'व्याख्या छिपाएं ▲',
              'explanation_provenance': 'व्याख्या एवं स्रोत ▼',
              'suggested_verification': 'सुझाया गया सत्यापन प्रश्न',
              'general_review': 'सामान्य समीक्षा',
              'payment_terms': 'भुगतान की शर्तें',
              'lawyer_questions': 'वकील के लिए प्रश्न',
              'amount': 'राशि',
              'currency': 'मुद्रा',
              'frequency': 'आवृत्ति',
              'effective_date': 'प्रभावी तिथि',
              'timing': 'समय',
              'condition': 'शर्त',
              'section': 'अनुभाग',
              'page': 'पृष्ठ',
              'not_specified': 'निर्दिष्ट नहीं है',
              'completeness_observation': 'पूर्णता अवलोकन',
              'notice_period': 'नोटिस अवधि',
              'payment_date': 'भुगतान की तिथि',
              'probation_service_period': 'परिवीक्षा / सेवा अवधि',
              'deadline': 'अंतिम तिथि',
              'temporal_obligation': 'समय दायित्व',
              'none_detected': 'कोई नहीं मिला',
              'no_structure_detected': 'कोई संरचना नहीं मिली',
              'no_signals_detected': 'इस दस्तावेज़ में कोई जोखिम संकेत नहीं मिले।',
              'no_relationships_detected': 'इस दस्तावेज़ में कोई क्लॉज़ संबंध नहीं मिले।',
              'no_financial_detected': 'इस दस्तावेज़ में कोई वित्तीय प्रावधान नहीं मिले।',
              'select_doc_a': 'दस्तावेज़ A चुनें...',
              'select_doc_b': 'दस्तावेज़ B चुनें...',
              'select_a_doc': 'एक दस्तावेज़ चुनें...',
              'all_changes': 'सभी परिवर्तन',
              'financial_change_label': 'वित्तीय परिवर्तन',
              'relationship_impact_label': 'संरचनात्मक प्रभाव',
              'explain_change_ai': 'एआई से परिवर्तन समझें',
              'clause_search_placeholder': 'दस्तावेज़ में खोजें...',
              'cited_evidence_quote': 'उद्धृत साक्ष्य का अंश:'},
    'kn': {   'app_title': 'ಲೆಕ್ಸಿಗಾರ್ಡ್ — ಕಾನೂನು ದಾಖಲೆಗಳ ಇಂಟೆಲಿಜೆನ್ಸ್',
              'dashboard': 'ಡ್ಯಾಶ್\u200cಬೋರ್ಡ್',
              'analyze': 'ವಿಶ್ಲೇಷಿಸಿ',
              'ask': 'ಪ್ರಶ್ನಿಸಿ',
              'compare': 'ಹೋಲಿಸಿ',
              'workspace': 'ಕಾರ್ಯಕ್ಷೇತ್ರ',
              'prepare': 'ಸಿದ್ಧತೆ',
              'reports': 'ವರದಿಗಳು',
              'reminders': 'ಜ್ಞಾಪನೆಗಳು ಮತ್ತು ಕ್ಯಾಲೆಂಡರ್',
              'overview': 'ಅವಲೋಕನ',
              'attention_signals': 'ಗಮನಾರ್ಹ ಸಂಕೇತಗಳು',
              'relationships': 'ಖಂಡಗಳ ಸಂಬಂಧಗಳು',
              'financial_compensation': 'ಆರ್ಥಿಕ ಮತ್ತು ಪರಿಹಾರ',
              'clauses': 'ಖಂಡಗಳು',
              'consistency': 'ಸಾಂಗತ್ಯ ಎಂಜಿನ್',
              'view_source': 'ಮೂಲ ಖಂಡವನ್ನು ವೀಕ್ಷಿಸಿ',
              'view_related': 'ಸಂಬಂಧಿತ ಖಂಡವನ್ನು ವೀಕ್ಷಿಸಿ',
              'explain_ai': 'ಎಐ ಮೂಲಕ ವಿವರಿಸಿ',
              'explain_again': 'ಮತ್ತೆ ವಿವರಿಸಿ',
              'export_report': 'ವರದಿ ರಫ್ತು ಮಾಡಿ',
              'export_pdf': 'ಪಿಡಿಎಫ್ ವರದಿ ಡೌನ್\u200cಲೋಡ್ ಮಾಡಿ',
              'export_json': 'ಜೆಸನ್ ಡೇಟಾ ರಫ್ತು ಮಾಡಿ',
              'export_ics': 'ಕ್ಯಾಲೆಂಡರ್ (.ics) ರಫ್ತು ಮಾಡಿ',
              'no_results': 'ಯಾವುದೇ ಸೂಕ್ತ ವಿವರಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
              'insufficient_evidence': 'ಅಪ್\u200cಲೋಡ್ ಮಾಡಿದ ದಾಖಲೆಯಲ್ಲಿ ಅಗತ್ಯ ಸಾಕ್ಷ್ಯಗಳಿಲ್ಲ.',
              'potential_asymmetry': 'ಸಾಧ್ಯವಿರುವ ಅಸಮತೋಲನ',
              'balanced_relationship': 'ಸಮತೋಲಿತ ಸಂಬಂಧ',
              'missing_counterpart': 'ಅನುಪಸ್ಥಿತ ಪ್ರತಿಯೊಂದು ಭಾಗ',
              'disclaimer_title': 'ಕಾನೂನು ಹಕ್ಕುತ್ಯಾಗ',
              'disclaimer_text': 'ಲೆಕ್ಸಿಗಾರ್ಡ್ ದಾಖಲೆಗಳ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಸಾಕ್ಷ್ಯಾಧಾರಿತ ವಿವರಣೆಗಳನ್ನು ನೀಡುತ್ತದೆ. ಇದು '
                                 'ಕಾನೂನು ಸಲಹೆಯಲ್ಲ.',
              'hero_title': 'ನಿಮ್ಮ ಕಾನೂನು ದಾಖಲೆಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ',
              'hero_subtitle': 'ಅಪಾಯಗಳನ್ನು ನೋಡಿ. ಉತ್ತಮ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಿ. ಸುರಕ್ಷಿತವಾಗಿರಿ.',
              'upload_title': 'ನಿಮ್ಮ ದಾಖಲೆಯನ್ನು ಇಲ್ಲಿ ಡ್ರಾಗ್ ಮಾಡಿ ಹಾಕಿ',
              'upload_hint': 'PDF, DOCX, TXT 10MB ವರೆಗೆ ಬೆಂಬಲಿಸುತ್ತದೆ',
              'browse_files': 'ಫೈಲ್\u200cಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
              'recent_documents': 'ಇತ್ತೀಚಿನ ದಾಖಲೆಗಳು',
              'documents': 'ದಾಖಲೆಗಳು',
              'upload': 'ಅಪ್\u200cಲೋಡ್',
              'open': 'ತೆರೆಯಿರಿ',
              'delete': 'ಅಳಿಸಿ',
              'pages': 'ಪುಟಗಳು',
              'financial_items': 'ಹಣಕಾಸು ಐಟಂಗಳು',
              'generate_summary': 'ಸಾರಾಂಶ ರಚಿಸಿ',
              'ai_summary': 'ಎಐ ಸಾರಾಂಶ',
              'doc_map': 'ದಾಖಲೆ ಮ್ಯಾಪ್',
              'important_dates': 'ಪ್ರಮುಖ ದಿನಾಂಕಗಳು',
              'key_obligations': 'ಪ್ರಮುಖ ಬಾಧ್ಯತೆಗಳು',
              'ask_title': 'ನಿಮ್ಮ ದಾಖಲೆಯ ಬಗ್ಗೆ ಪ್ರಶ್ನೆ ಕೇಳಿ',
              'ask_placeholder': 'ನಿಮ್ಮ ಕಾನೂನು ಪ್ರಶ್ನೆಯನ್ನು ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...',
              'send': 'ಕಳುಹಿಸಿ',
              'compare_docs': 'ದಾಖಲೆಗಳನ್ನು ಹೋಲಿಸಿ',
              'orig_doc': 'ಮೂಲ ದಾಖಲೆ (ದಾಖಲೆ A)',
              'revised_doc': 'ಪರಿಷ್ಕೃತ ದಾಖಲೆ (ದಾಖಲೆ B)',
              'btn_compare': 'ದಾಖಲೆಗಳನ್ನು ಹೋಲಿಸಿ',
              'added': 'ಸೇರಿಸಲಾಗಿದೆ',
              'removed': 'ತೆಗೆದುಹಾಕಲಾಗಿದೆ',
              'modified': 'ಪರಿಷ್ಕರಿಸಲಾಗಿದೆ',
              'unchanged': 'ಬದಲಾಗದ',
              'prep_review': 'ಸಿದ್ಧತೆ ಮತ್ತು ಪರಿಶೀಲನೆ',
              'gen_checklist': 'ಕಾನೂನು ಪರಿಶೀಲನಾ ಪಟ್ಟಿಯನ್ನು ರಚಿಸಿ',
              'copy_clipboard': 'ಕ್ಲಿಪ್\u200cಬೋರ್ಡ್\u200cಗೆ ನಕಲಿಸಿ',
              'evidence_viewer': 'ದಾಖಲೆ ಸಾಕ್ಷ್ಯ ವೀಕ್ಷಕ',
              'doc_overview_title': 'ದಾಖಲೆಯ ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವಿಕೆ ಅವಲೋಕನ',
              'risk_signals': 'ಅಪಾಯದ ಸಂಕೇತಗಳು',
              'monetary_values': 'ಹಣಕಾಸು ಮೌಲ್ಯಗಳು',
              'contracting_parties': 'ಒಪ್ಪಂದದ ಪಕ್ಷಗಳು',
              'dates_temporal_title': 'ಪ್ರಮುಖ ದಿನಾಂಕಗಳು ಮತ್ತು ಸಮಯ ಬಾಧ್ಯತೆಗಳು',
              'review': 'ಪರಿಶೀಲಿಸಿ',
              'confirm_obligation': 'ಬಾಧ್ಯತೆಯನ್ನು ಖಚಿತಪಡಿಸಿ',
              'track_date': 'ಪ್ರಮುಖ ದಿನಾಂಕವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
              'view_in_doc': 'ದಾಖಲೆಯಲ್ಲಿ ವೀಕ್ಷಿಸಿ',
              'why_seeing_this': 'ನಾನು ಇದನ್ನು ಏಕೆ ನೋಡುತ್ತಿದ್ದೇನೆ? ▼',
              'hide_explanation': 'ವಿವರಣೆ ಮರೆಮಾಡಿ ▲',
              'explanation_provenance': 'ವಿವರಣೆ ಮತ್ತು ಉಗಮ ▼',
              'suggested_verification': 'ಸೂಚಿಸಿದ ಪರಿಶೀಲನಾ ಪ್ರಶ್ನೆ',
              'general_review': 'ಸಾಮಾನ್ಯ ಪರಿಶೀಲನೆ',
              'payment_terms': 'ಪಾವತಿ ನಿಯಮಗಳು',
              'lawyer_questions': 'ವಕೀಲರಿಗೆ ಪ್ರಶ್ನೆಗಳು',
              'amount': 'ಮೊತ್ತ',
              'currency': 'ಕರೆನ್ಸಿ',
              'frequency': 'ಆವರ್ತನ',
              'effective_date': 'ಪರಿಣಾಮಕಾರಿ ದಿನಾಂಕ',
              'timing': 'ಸಮಯ',
              'condition': 'ಷರತ್ತು',
              'section': 'ವಿಭಾಗ',
              'page': 'ಪುಟ',
              'not_specified': 'ಉಲ್ಲೇಖಿಸಲಾಗಿಲ್ಲ',
              'completeness_observation': 'ಪೂರ್ಣತೆಯ ವೀಕ್ಷಣೆ',
              'notice_period': 'ನೋಟಿಸ್ ಅವಧಿ',
              'payment_date': 'ಪಾವತಿ ದಿನಾಂಕ',
              'probation_service_period': 'ಪರಿವೀಕ್ಷಣಾ / ಸೇವಾ ಅವಧಿ',
              'deadline': 'ಕೊನೆಯ ದಿನಾಂಕ',
              'temporal_obligation': 'ಸಮಯ ಬಾಧ್ಯತೆ',
              'none_detected': 'ಯಾವುದೂ ಕಂಡುಬಂದಿಲ್ಲ',
              'no_structure_detected': 'ಯಾವುದೇ ರಚನೆ ಕಂಡುಬಂದಿಲ್ಲ',
              'no_signals_detected': 'ಈ ದಾಖಲೆಯಲ್ಲಿ ಯಾವುದೇ ಗಮನಾರ್ಹ ಸಂಕೇತಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
              'no_relationships_detected': 'ಈ ದಾಖಲೆಯಲ್ಲಿ ಯಾವುದೇ ಸಂಬಂಧಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
              'no_financial_detected': 'ಈ ದಾಖಲೆಯಲ್ಲಿ ಯಾವುದೇ ಹಣಕಾಸು ವಿವರಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
              'select_doc_a': 'ದಾಖಲೆ A (ಮೂಲ) ಆಯ್ಕೆಮಾಡಿ...',
              'select_doc_b': 'ದಾಖಲೆ B (ಪರಿಷ್ಕೃತ) ಆಯ್ಕೆಮಾಡಿ...',
              'select_a_doc': 'ದಾಖಲೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ...',
              'all_changes': 'ಎಲ್ಲಾ ಬದಲಾವಣೆಗಳು',
              'financial_change_label': 'ಹಣಕಾಸು ಬದಲಾವಣೆ',
              'relationship_impact_label': 'ರಚನಾತ್ಮಕ ಪರಿಣಾಮ',
              'explain_change_ai': 'ಎಐ ಮೂಲಕ ಬದಲಾವಣೆ ವಿವರಿಸಿ',
              'clause_search_placeholder': 'ದಾಖಲೆಯನ್ನು ಹುಡುಕಿ...',
              'cited_evidence_quote': 'ಉಲ್ಲೇಖಿತ ಸಾಕ್ಷ್ಯ ಉದ್ಧರಣ:'},
    'te': {   'app_title': 'లెక్సిగార్డ్ — న్యాయపరమైన డాక్యుమెంట్ ఇంటెలిజెన్స్',
              'dashboard': 'డాష్\u200cబోర్డ్',
              'analyze': 'విశ్లేషించండి',
              'ask': 'ప్రశ్నించండి',
              'compare': 'పోల్చండి',
              'workspace': 'వర్క్\u200cస్పేస్',
              'prepare': 'సిద్ధత',
              'reports': 'నివేదికలు',
              'reminders': 'జ్ఞాపికలు & క్యాలెండర్',
              'overview': 'అవలోకనం',
              'attention_signals': 'శ్రద్ధ వహించాల్సిన సంకేతాలు',
              'relationships': 'క్లాజ్ సంబంధాలు',
              'financial_compensation': 'ఆర్థిక & నష్టపరిహారం',
              'clauses': 'క్లాజులు',
              'consistency': 'సంగతత ఇంజిన్',
              'view_source': 'మూల క్లాజ్ చూడండి',
              'view_related': 'సంబంధిత క్లాజ్ చూడండి',
              'explain_ai': 'ఎఐతో వివరణ',
              'explain_again': 'మళ్లీ వివరించండి',
              'export_report': 'రిపోర్ట్ ఎగుమతి చేయండి',
              'export_pdf': 'పిడిఎఫ్ రిపోర్ట్ డౌన్\u200cలోడ్ చేయండి',
              'export_json': 'జెసన్ డేటా ఎగుమతి చేయండి',
              'export_ics': 'క్యాలెండర్ (.ics) ఎగుమతి చేయండి',
              'no_results': 'సంబంధిత నిబంధనలేవీ లభించలేదు.',
              'insufficient_evidence': 'అప్\u200cలోడ్ చేసిన డాక్యుమెంట్\u200cలో తగినంత ఆధారం లేదు.',
              'potential_asymmetry': 'సాధ్యమయ్యే అసమానత',
              'balanced_relationship': 'సమతుల్య సంబంధం',
              'missing_counterpart': 'అనుపస్థిత ప్రతిరూపం',
              'disclaimer_title': 'న్యాయపరమైన నిరాకరణ',
              'disclaimer_text': 'లెక్సిగార్డ్ డాక్యుమెంట్ విశ్లేషణ మరియు సాక్ష్యాధారిత వివరణలను అందిస్తుంది. ఇది '
                                 'న్యాయ సలహా కాదు.',
              'hero_title': 'మీ న్యాయపరమైన డాక్యుమెంట్\u200cలను అర్థం చేసుకోండి',
              'hero_subtitle': 'రిస్క్\u200cలను చూడండి. మంచి ప్రశ్నలు అడగండి. సురక్షితంగా ఉండండి.',
              'upload_title': 'మీ డాక్యుమెంట్\u200cను ఇక్కడ డ్రాగ్ చేసి వేయండి',
              'upload_hint': 'PDF, DOCX, TXT 10MB వరకు సపోర్ట్ చేస్తుంది',
              'browse_files': 'ఫైళ్లను బ్రౌజ్ చేయండి',
              'recent_documents': 'ఇటీవలి డాక్యుమెంట్\u200cలు',
              'documents': 'డాక్యుమెంట్\u200cలు',
              'upload': 'అప్\u200cలోడ్',
              'open': 'ఓపెన్',
              'delete': 'తొలగించండి',
              'pages': 'పేజీలు',
              'financial_items': 'ఆర్థిక అంశాలు',
              'generate_summary': 'సారాంశం సృష్టించండి',
              'ai_summary': 'ఎఐ సారాంశం',
              'doc_map': 'డాక్యుమెంట్ మ్యాప్',
              'important_dates': 'ముఖ్యమైన తేదీలు',
              'key_obligations': 'కీలక బాధ్యతలు',
              'ask_title': 'మీ డాక్యుమెంట్ గురించి ప్రశ్న అడగండి',
              'ask_placeholder': 'మీ న్యాయపరమైన ప్రశ్నను ఇక్కడ టైప్ చేయండి...',
              'send': 'పంపండి',
              'compare_docs': 'డాక్యుమెంట్\u200cలను పోల్చండి',
              'orig_doc': 'మూల డాక్యుమెంట్ (డాక్యుమెంట్ A)',
              'revised_doc': 'సవరించిన డాక్యుమెంట్ (డాక్యుమెంట్ B)',
              'btn_compare': 'డాక్యుమెంట్\u200cలను పోల్చండి',
              'added': 'జోడించబడింది',
              'removed': 'తొలగించబడింది',
              'modified': 'సవరించబడింది',
              'unchanged': 'మార్పులేని',
              'prep_review': 'సిద్ధత మరియు సమీక్ష',
              'gen_checklist': 'న్యాయ సమీక్ష చెక్\u200cలిస్ట్ సృష్టించండి',
              'copy_clipboard': 'క్లిప్\u200cబోర్డ్\u200cకి కాపీ చేయండి',
              'evidence_viewer': 'డాక్యుమెంట్ ఆధారాల వీక్షకం',
              'doc_overview_title': 'డాక్యుమెంట్ అవగాహన అవలోకనం',
              'risk_signals': 'రిస్క్ సంకేతాలు',
              'monetary_values': 'ఆర్థిక విలువలు',
              'contracting_parties': 'ఒప్పంద పక్షాలు',
              'dates_temporal_title': 'ముఖ్యమైన తేదీలు & సమయ బాధ్యతలు',
              'review': 'సమీక్షించండి',
              'confirm_obligation': 'బాధ్యతను ధృవీకరించండి',
              'track_date': 'ముఖ్యమైన తేదీని ట్రాక్ చేయండి',
              'view_in_doc': 'డాక్యుమెంట్\u200cలో చూడండి',
              'why_seeing_this': 'నేను దీనిని ఎందుకు చూస్తున్నాను? ▼',
              'hide_explanation': 'వివరణ దాచండి ▲',
              'explanation_provenance': 'వివరణ & మూలం ▼',
              'suggested_verification': 'సూచించిన పరిశీలన ప్రశ్న',
              'general_review': 'సాధారణ సమీక్ష',
              'payment_terms': 'చెల్లింపు నిబంధనలు',
              'lawyer_questions': 'లాయర్ కోసం ప్రశ్నలు',
              'amount': 'మొత్తం',
              'currency': 'కరెన్సీ',
              'frequency': 'ఫ్రీక్వెన్సీ',
              'effective_date': 'అమలు తేదీ',
              'timing': 'సమయం',
              'condition': 'షరతు',
              'section': 'విభాగం',
              'page': 'పేజీ',
              'not_specified': 'పేర్కొనబడలేదు',
              'completeness_observation': 'పూర్తిస్థాయి పరిశీలన',
              'notice_period': 'నోటీసు వ్యవధి',
              'payment_date': 'చెల్లింపు తేదీ',
              'probation_service_period': 'ప్రొబేషన్ / సేవా వ్యవధి',
              'deadline': 'గడువు తేదీ',
              'temporal_obligation': 'సమయ బాధ్యత',
              'none_detected': 'ఏమీ లభించలేదు',
              'no_structure_detected': 'ఎటువంటి నిర్మాణం లభించలేదు',
              'no_signals_detected': 'ఈ డాక్యుమెంట్\u200cలో ఎటువంటి రిస్క్ సంకేతాలు లభించలేదు.',
              'no_relationships_detected': 'ఈ డాక్యుమెంట్\u200cలో ఎటువంటి క్లాజ్ సంబంధాలు లభించలేదు.',
              'no_financial_detected': 'ఈ డాక్యుమెంట్\u200cలో ఎటువంటి ఆర్థిక అంశాలు లభించలేదు.',
              'select_doc_a': 'డాక్యుమెంట్ A ఎంచుకోండి...',
              'select_doc_b': 'డాక్యుమెంట్ B ఎంచుకోండి...',
              'select_a_doc': 'ఒక డాక్యుమెంట్ ఎంచుకోండి...',
              'all_changes': 'అన్ని మార్పులు',
              'financial_change_label': 'ఆర్థిక మార్పు',
              'relationship_impact_label': 'నిర్మాణాత్మక ప్రభావం',
              'explain_change_ai': 'ఎఐతో మార్పు వివరణ',
              'clause_search_placeholder': 'డాక్యుమెంట్\u200cలో శోధించండి...',
              'cited_evidence_quote': 'ఉదాహరించిన ఆధారాల ఉల్లేఖన:'}}

def get_translation(key: str, lang: str = "en") -> str:
    """Retrieve UI string in English."""
    return UI_TRANSLATIONS["en"].get(key, key)


def get_all_translations(lang: str = "en") -> Dict[str, str]:
    """Retrieve static UI dictionary in English."""
    return dict(UI_TRANSLATIONS["en"])
